services:
  mongodb:
    image: mongo:jammy
    ports:
      - "27017:27017"
    volumes:
      - ./db_data/:/data/db/
      - /etc/timezone:/etc/timezone:ro
    networks:
      - buspass_network
    container_name: mongodb

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - buspass_network
    container_name: mongoexpress

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    networks:
      - buspass_network
    container_name: server

  client:
    build:
      context: ./client
    volumes:
      - ./client/src:/app/src
    ports:
      - '8080:8080'
    depends_on:
      - server
    networks:
      - buspass_network
    container_name: client

  core:
    image: nginx:stable-alpine3.19
    build:
      context: ./core
      dockerfile: Dockerfile
    depends_on:
      - client
      - server
      - mongodb
    volumes:
      - ./core/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - buspass_network
    ports:
      - 80:80
    container_name: core

networks:
  buspass_network:
